#!/bin/bash
# rgbmatrix install script, for FlightGazer.
# Installs the latest version of the rgbmatrix library
# and makes it available as a system-wide Python module.
# This will only build on a Raspberry Pi!
# Last updated: v.9.8.0 (January 2026)
# By: WeegeeNumbuh1

GREEN='\033[0;32m'
ORANGE='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color
FADE='\033[2m'
BASEDIR=$(cd `dirname -- $0` && pwd)
export PIP_ROOT_USER_ACTION=ignore
GITUSER='https://github.com/hzeller'
REPO='rpi-rgb-led-matrix'
# this fixes an issue when using PIL >= 12 and allows building with Python >= 3.12
COMMIT=3a5d753e91f40e24e6ae2041fac95946e7a81767

echo -ne "\033]0;rgbmatrix installer\007" # set window title
echo -e "\n${ORANGE}>>> Welcome to the rgbmatrix installer! (for FlightGazer)${NC}"

if [ `id -u` -ne 0 ]; then
	>&2 echo -e "${RED}>>> ERROR: This script must be run as root.${NC}"
	sleep 1s
	exit 1
fi

if [ ! -f "${BASEDIR}/../FlightGazer-init.sh" ]; then
	>&2 echo -e "${RED}>>> ERROR: Could not find the FlightGazer initialization script!${NC}"
	echo "This file needs to be in the utilities directory of FlightGazer!"
	echo "This file is running in: ${BASEDIR}"
	exit 1
fi

if [ -f '/sys/firmware/devicetree/base/model' ] && grep -q 'Raspberry Pi' /proc/cpuinfo; then
	DEV_TYPE=$(tr -d '\0' < /sys/firmware/devicetree/base/model) >/dev/null 2>&1
	# https://stackoverflow.com/a/46163928
	# https://raspberrypi.stackexchange.com/a/61071
	case "$DEV_TYPE" in
		*"Pi 5"*)
			PI5=true
			;;
		*)
			PI5=false
			;;
	esac
else
	echo -e "${RED}>>> ERROR: The rgbmatrix library is only meant for the Raspberry Pi!\n${NC}"
	echo "No changes have been made to this system."
	exit 1
fi
if [ ! -f "${BASEDIR}/rgbmatrix_check.py" ]; then
	RGBMATRIX_PRESENT=10 # some other number that isn't a return code generated by the script
else
	python3 "${BASEDIR}/rgbmatrix_check.py" >/dev/null 2>&1
	RGBMATRIX_PRESENT=$?
fi
# Redirect output to a logfile
exec > >(tee -a "${BASEDIR}/../rgbmatrix-install.log") 2>&1
time_now=$(date '+%Y-%m-%d %H:%M')

echo "**********************************************************"
echo "> Script start: ${time_now}"
echo "> Running on a ${DEV_TYPE}"
echo ""
echo -n "> rgbmatrix library: "
if [ $RGBMATRIX_PRESENT -eq 0 ]; then
	echo "Installed"
	echo ""
	echo "Running this script will update your current rgbmatrix"
	echo "install to the latest one available."
elif [ $RGBMATRIX_PRESENT -eq 1 ]; then
	echo "Unavailable"
	echo ""
	echo "Continuing with this install will disable audio and"
	echo "configure the kernel to reserve one CPU core just for"
	echo "the rgbmatrix display, if it's not configured already."
elif [ $RGBMATRIX_PRESENT -eq 3 ]; then
	echo "Present, but not available system-wide"
	echo ""
	echo "Running this script will update your current rgbmatrix"
	echo "install to the latest one available and make it"
	echo "available as a system-wide Python module."
else
	echo "Status cannot be determined"
	echo ""
	echo "Continuing with this install will disable audio and"
	echo "configure the kernel to reserve one CPU core just for"
	echo "the rgbmatrix display, if it's not configured already."
fi
echo "**********************************************************"
if [ "$PI5" = true ]; then
	echo -e "${ORANGE}> Notice: rgbmatrix may not work with a Raspberry Pi 5. The install will continue, however.${NC}"
fi
sleep 5s
echo "Starting soon... (press Ctrl+C to cancel this install now)"
sleep 10s

echo -e "\n${GREEN}>>> Starting the rgbmatrix install...${NC}"
read -r OWNER_OF_FGDIR GROUP_OF_FGDIR <<<$(stat -c "%U %G" "${BASEDIR}")
echo "> Determining the home directory..."
USER_HOME=$(sudo -u "$OWNER_OF_FGDIR" sh -c 'echo $HOME') >/dev/null 2>&1
# https://superuser.com/a/1613980
echo -e "> ${USER_HOME}"
RGB_MATRIX_DIR="${USER_HOME}/rpi-rgb-led-matrix"
echo -e "> Installing to ${RGB_MATRIX_DIR}"

echo -e "\n${GREEN}>>> Installing needed dependencies...${NC}"
echo -e "> Updating packages...${FADE}"
apt-get update
echo -e "${NC}> Doing the install... (this might take some time)${FADE}"
apt-cache --generate pkgnames | \
grep --line-regexp --fixed-strings \
	-e make \
	-e gcc \
	-e g++ \
	-e python3-dev \
	-e python3-pip \
	-e python3-venv \
	-e python3-pillow \
	-e python3-tk \
	-e cython3 \
	| xargs apt-get install -y
echo -e "${NC}> Dependency install complete.${FADE}"

if [ -d "$RGB_MATRIX_DIR" ]; then
	echo "> An existing install of the rgbmatrix library is present."
	echo "  > Backing this folder up to 'rpi-rgb-led-matrix_old'..."
	rm -rf "${USER_HOME}/rpi-rgb-led-matrix_old" 2>&1 >/dev/null
	mv "$RGB_MATRIX_DIR" "${USER_HOME}/rpi-rgb-led-matrix_old"
fi

echo -e "> Downloading RGB matrix software...\n${FADE}"
rm -rf "$RGB_MATRIX_DIR" 2>&1 >/dev/null # remove anything existing
git clone --depth=1 $GITUSER/$REPO "$RGB_MATRIX_DIR"
# uncomment the lines below AND comment out the line above
# to use the specific commit at the top of this script

# curl -L $GITUSER/$REPO/archive/$COMMIT.zip -o /tmp/$REPO-$COMMIT.zip\
# && unzip -q /tmp/$REPO-$COMMIT.zip\
# && rm /tmp/$REPO-$COMMIT.zip && mv /tmp/$REPO-$COMMIT "$RGB_MATRIX_DIR"

if [ $? -ne 0 ]; then
	echo -e "${RED}>>> ERROR: Failed to download from GitHub. Cannot continue.${NC}"
	echo "Undoing changes..."
	rm -rf "$RGB_MATRIX_DIR" 2>&1 >/dev/null
	if [ -d "${USER_HOME}/rpi-rgb-led-matrix_old" ]; then
		mv "${USER_HOME}/rpi-rgb-led-matrix_old" "$RGB_MATRIX_DIR"
	fi
	echo "Done. Try running this script at a later time."
	exit 1
fi
echo -e "\n${GREEN}>>> Building RGB matrix software..."
echo -e "${ORANGE}(This will take a few minutes)\n${NC}${FADE}"
cd "$RGB_MATRIX_DIR"
make clean
make build-python
echo -e "${NC}> Build complete."
echo -e "${GREEN}>>> Installing python library...${NC}"
cd bindings/python
pip install . --use-pep517 --break-system-packages
if [ $? -ne 0 ]; then
	echo -e "${RED}>>> RGB-Matrix python installation failed!${NC}"
	echo "FlightGazer may still be able to use rgbmatrix, however."
	exit 1
fi
echo -e "${GREEN}>>> Configuring the system...${NC}"
chown -Rf ${OWNER_OF_FGDIR}:${GROUP_OF_FGDIR} "$RGB_MATRIX_DIR" >/dev/null 2>&1
# below taken from https://github.com/MLB-LED-Scoreboard/mlb-led-scoreboard/blob/master/install.sh
if [ ! -f '/etc/modprobe.d/blacklist-rgbmatrix.conf' ]; then
	echo "> Sound blacklist file not found, creating."
	echo "blacklist snd_bcm2835" | tee /etc/modprobe.d/blacklist-rgbmatrix.conf
	modprobe -r snd_bcm2835
	depmod -a
else
	echo "> Sound blacklist file found, skipping creation."
fi
if grep -q isolcpus=3 "/boot/cmdline.txt" || grep -q isolcpus=3 "/boot/firmware/cmdline.txt" 2>/dev/null; then
	echo "> isolcpus=3 found in cmdline.txt"
else
	read -d . VERSION < /etc/debian_version
	if [ "$VERSION" -lt "12" ]; then
		echo "> adding isolcpus=3 to /boot/cmdline.txt"
		sed -i '$ s/$/ isolcpus=3/' /boot/cmdline.txt
	else
		echo "> adding isolcpus=3 to /boot/firmware/cmdline.txt"
		sed -i '$ s/$/ isolcpus=3/' /boot/firmware/cmdline.txt
	fi
fi
echo -e "${GREEN}>>> RGB-Matrix successfully installed!${NC}"
if [ $RGBMATRIX_PRESENT -ne 0 ]; then
	echo "You might need to reboot your system to use the"
	echo "rgbmatrix library."
fi
echo "rgbmatrix install script exiting...."
exit 0